### ISSUE TITLE
[super] dpm publish

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpm-py#1]
```
cd data/package/directory
dpm publish
```
### Publisher Name

How do we know publisher name and package name for publishing?

Answer: we assume by default we are always working with scoped packages. These packages have a name field like:

```
{
  "name": "[@]{publisher}/{name}"    # note @ is optional
}
```

If package is _not_ scoped then use the username as the publisher name.
## Tasks

This a very big item covering many steps:
- [x] Check I am in a data package directory (is there a datapackage.json) - #12 
- [x] Validate datapackage is ok - not just exists #15
- [x] Check local credentials - in .dpm or similar #18 
  - [x] … (and instructions to configure) - #2 
- [x] Authenticate using credentials and get session token #13 
- [x] Send metadata (datapackage.json) via API #14 
- [x] Upload each data file - #6 
- [x] Finalizing request: everything done - is everything ok at server end
- [ ] Report success - perhaps report where data package now appears in the frontend
## Interaction Diagram

<img src="https://docs.google.com/drawings/d/1lZdZtDOvEAm8MVpdVsLaOHc5da6Sxtg-cQ34WtemKZo/pub?w=1153&h=735" />

**Comment by Fak3** [comment]
This was implemented as described.
