### ISSUE TITLE
OKI code review

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/dpm-py#41]
- [x] tests are failing on travis
- [x] Several [issues with the client](https://github.com/frictionlessdata/dpm-py/tree/master/dpm/client) **have created #43 for this**
  - [x] A seperation was attempted between CLI interface the application logic after my suggestion on the same. But, much of the client still uses `click` functions, and `sys.exit`, and in general is still written as if it is to be run in the shell. The result is that it is not very useful as a python client lib.
  - [x] While `do_publish` and `do_validate` exhibit the above, `do_configure` is littered with `print` and does not, for example, do something useful like return the file path for the config, or the config object itself. Small things that could make a big difference if this is to be used as a python client
- [x] [`DEFAULT_SERVER` config](https://github.com/frictionlessdata/dpm-py/blob/master/dpm/constants.py#L12) with no way to override it?
  - #44 
- [x] Can you pls use the OKI method for [setting a package's version](https://github.com/frictionlessdata/dpm-py/blob/master/dpm/main.py#L23)
- [x] All the config fallbacks should be consolidated in the config file itself, and not spread in codebase. [Example of config conditionals outside of config](https://github.com/frictionlessdata/dpm-py/blob/master/dpm/main.py#L42)
   - #44 
- [x] Publishing [requires username and password on each publish action](https://github.com/frictionlessdata/dpm-py/blob/master/dpm/main.py#L82). Yet we do use [jwt](https://github.com/frictionlessdata/dpm-py/blob/333c6165d251419c278e863c2a8355fe65dee162/dpm/runtime.py#L21) elsewhere. Please explain how auth/z works, and document it in the README. I don't understand why we'd want to use the password at all, once we have a jwt.
   - NOT SURE WHAT WE WILL DO - #45 is doc improvements only
- [ ] Please set up travis to [deploy the package itself](https://github.com/frictionlessdata/dpm-py/blob/master/.travis.yml#L1) to pypi. See the OKI examples for how.
  - #71  
- [x] Related to my first point, [all the tests depend on the CLI](https://github.com/frictionlessdata/dpm-py/tree/master/tests). Please test the CLI and the Python client.
  - #43 
- [ ] As I've noted [elsewhere](https://github.com/frictionlessdata/dpr-api/issues/5#issuecomment-256921136), it is an unusual design to not properly validate data packages locally before pushing them to the server. We can completely avoid a whole class of user interactions, [server error responses](https://github.com/frictionlessdata/dpm-py/blob/master/tests/test_publish_invalid.py#L18), and bad data quality, by doing this.
  - #46 
- [ ] The CLI only has two methods - [`validate` and `publish`](https://github.com/frictionlessdata/dpm-py/blob/master/dpm/main.py). The [requirements](https://docs.google.com/document/d/11M9FOh30hgLKiXyXLhfkVc8faqf22x6dKllXeuMG2lM/edit#heading=h.9jt9tsqpbu18) for the CLI are quite clear and much more extensive. 
   - *We have no plans to implement all of this. We went with user stories that were more minimal and focused on publish **only** (adding delete and purge later).*

**Comment by Fak3** [comment]
Travis build fixed (coveralls repo enabled after rename)

**Comment by rgrp** [comment]
@pwalsh 

> The CLI only has two methods - validate and publish. The requirements for the CLI are quite clear and much more extensive.

We have not had plans to implement all of this as we went with user stories that were more minimal and focused on publish **only**.

**Comment by pwalsh** [comment]
@rgrp the user stories are/where a way to order the requirements, not replace them. In any event, all but one of the API methods there are directly relevant to *publishers*: list, create, update, read, validate, delete.

**Comment by rgrp** [comment]
@pwalsh that was not how i had understood it. We did user stories and then picked prioritized ones. There is a bunch of stuff in the requirements that were not in the prioritized user stories. Let me be clear: I think requirements are good too - just not what we have been working off.

**Comment by pwalsh** [comment]
@rgrp currently, the validation of the DP is not profile-aware, and profile-specific validation is built into `datapackage-py` so is readily available. I think it would be useful. Likewise with data validation on the client (or server, if must) using `goodtables` or `jsontableschema.Table` - all the logic is there, and adding them to the client would ensure that the assumptions for tabular data on the server (vis, resource endpoints etc.) are safe assumptions to make.

**Comment by pwalsh** [comment]
@rgrp about long-lived JWT tokens, I'm not 100% sure myself. @akariv WDYT, and what do we do on OpenSpending?

**Comment by Fak3** [comment]
@pwalsh The dpm name is already taken on the pypi. Can we pick dpmpy or any other name to publish there? Or maybe someone can convince current owners to release it for us? (they seem to abandon it 4 years ago)

**Comment by pwalsh** [comment]
@Fak3 :). @rgrp owns `dpm` on pypi.

**Comment by rufuspollock** [comment]
@pwalsh I'm still stuck re pypi because i don't have access to my account anymore. I've requested access to my account again here https://sourceforge.net/p/pypi/support-requests/685/ (but that was 2m ago and nothing has moved!)

**Comment by rufuspollock** [comment]
FIXED. I'm closed as fixed. Remaining items are either blocked e.g. #71 or are items that are planned but not immediate e.g. local data validation #46 or the work on other commands.
