### ISSUE TITLE
[epic] Improve split of the client from the cli code

### ISSUE THREAD

**Issue by Fak3** [frictionlessdata/dpm-py#43]
It was noted in #41 and elsewhere that a client library is a useful thing. The code can be organized in a way that cli is built on top of an internal client library.

## Plan of action

* [x] Create a `Client` object in https://github.com/frictionlessdata/dpm-py/blob/master/dpm/client/__init__.py
* [x] Implement `__init__` - with a test
  * [x] load config
  * [x] load data package (and check one exists)
* [x] Implement `api_call` - with a test
  * [x] add tests for connection errors
* [x] Implement `ensure_auth` and store token so it can be used by `api_call`
  * [ ] Add tests (#56)
* [x] Refactor `validate` method into the client (and remove `do_validate.py`)
* [x] Refactor `publish` ... 
  * [x] add general success test
  * [ ] add tests for _upload_file (#57)
  * [ ] add test for publishing invalid datapackage.json (server reject) (#58)
* [x] Refactor `configure` method out of client to cli for now
  * [x] Remove username validation check - if it is wrong they will know when they try to authenticate!
* [x] Finally refactor the existing command line code to use the new client (#55)

## Code Sample

```python

# in cli
def publish()
    # token comes from authenticate decorator
    client = Client(path=self.datapackage_path, =self.token)
    client.publish()

# in client
class Client:
    def publish(self):
        self.ensure_authenticated()
    
        # post datapackage.json
        self.api_call(....)
        
        for resource in self.resources:
            self._upload_file_to_bitstore(...)
```

### More detailed example

```python
class Client(object):
    # try and get away without using click much for now
    # use exceptions and do not print of status updates - only remaining use is progressbar
    def __init__(data_package_path=None, config_path="~/.dpm/config", click=None):
        dp_path = data_package_path or os.getcwdir()
        # may want to use the datapackage-py here
        self.datapackage = _load_dp(data_package_path)
        # load config ... 
        self.config = self._load_config()
        self.click = click
    
    def _authenticate(self):
        # ok
        return True
        # failure
        raise Exception('...')
        
    def _api_call(self, ...):
        ... 
        
    def validate():
        # may want to throw an exception (?)
        return self.datapackage.validate()
        
    # this might not be worth having in the client - it can just live in the CLI ... 
    def configure()
        ... 
    
    # @authenticate # just call a method in code for now 
    def publish(self):
        self.ensure_auth() # nicer actually
        # can add back in future if we need
        # self.click.echo('Hooray - we authenticated!')
        
        self.validate()
        
        # do datapackage.json
        self.api_call(...)
        
        # do resources
        for resource in self.datapackage.resources:
            path = resource.path
            self._upload_to_bitstore(resource.path)
```

**cli**

```
@click.option('--config', 'configfile', default=configfile,
              help='Use custom config file. Default ~/.dpm/config')
@click.option('--datapackage', 'datapackage', default=None,
              help='Use custom data package file.')
@click.pass_context
def cli(ctx, configfile, debug):
    ctx.client = Client(datapackage, configfile)

@cli.command()
def publish():
    echo('Publishing!')
    try:
        out = ctx.client.publish()
    except:
        # handle error
    echo('Published OK')
    echo('Your package will be live at: %s' % out.details.location ...)

# Usage
dpmpy publish
dpmpy --config xyz publish
dpmpy --datapackage xyz/abc delete

# not supported for now
dpmpy publish --datapackage some/pak
```

## Why do we create a separation of CLI and Library?

Pros:

- Cleaner to test - and maybe easier too
- Get a clean library section
  - which we could backport to datapackage-py if we want later
- Conceptually nicer (?)

Cons

- More effort and more to read. Someone has to open up both.
- We cannot use the click utils like `echo` and progress bars (or we have to find a way to inject these in).
  - However this is not a big problem and kind of good to have a separation

**Original info from Paul Walsh**

I notice you are writing your logic directly in click functions. For example: https://github.com/frictionlessdata/dpmpy/blob/master/dpm/main.py#L41 and that is why your tests need to use the click test runner. would be easier for unit testing if you write them in a lib that mimics the click-based API. and calls that. e.g.:

```
from . import client

@click.command
def config(*args, **kwargs):
    client.config(*args, **kwargs)
    # reformat the response for shell if desired


@click.command
def validate(*args, **kwargs):
    client.validate(*args, **kwargs)
    # reformat the response for shell if desired
```

It also means the design implements a python lib as well as a CLI.

I’ve seen, with my own code and others in the last year, that this type of pattern will be heaps easier to maintain and test.

**Comment by Fak3** [comment]
To my understanding as of now, we only implemented a tiny fraction of what the client should really do.  The dp versioning, cross-package dependencies, installation could make us rewrite 90% of code. At this stage it is really hard for me to come up with a solution for a nice client API. I will have to think about it more.

Possible inspirations: boto3

**Comment by Fak3** [comment]
Some problems and proposed solutions:
* To handle the configuration and auth I would suggest to make the client lib\API class-based, where the `DpmClient` instance is to be created and configured at the start by the lib user (as dmpmy cli)
* Passing the config and defaults to subcommands would be replaced by passing the instance of the client, kepping it responsible of config in one place. (to address #44)  
* Divorcing client lib from click would mean introduction of logging the messagess for the lib users(as dmpmy cli) to handle in a way they need.
I would suggest to use the structlog (it is flexible and blessed by the community) 
   * To still have the neat click progessbars, the dmpmy cli can override `on_file_upload()` method of the api client (by subclassing it)

**Comment by Fak3** [comment]
This refactoring will hopefully address #44 too

**Comment by Fak3** [comment]
It seems that a client could accept the needed config options as arguments of the constructor, there is little sense to pack it into a dict.

**Comment by Fak3** [comment]
api_call tests unvelied an issue with properly handling errors from requests. Fighting with it right now

**Comment by Fak3** [comment]
Things left to be done:
* Refactor cli to use new Client class [#55] (~3-4h)
* Add tests for Client._upload_file() [#57] (~3h)
* Add tests for Client._ensure_auth() [#56] (~1h)

**Comment by Fak3** [comment]
* Add test for publishing invalid datapackage.json (server reject) (#58) (~1h)

**Comment by Fak3** [comment]
Refactoring can be considered complete. Remaining tests will be addressed as separate issues.
