### ISSUE TITLE
Modify finalize method

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpm-py#82]
We need to make `dpmpy` compatible with open-spending. Below is the list of changes we need to make in publish process.

## Tasks

- [x] Remove datapackage.json upload [call](https://github.com/frictionlessdata/dpm-py/blob/master/dpm/client/__init__.py#L126)
- [x] Include datapackage.json in [file list](https://github.com/frictionlessdata/dpm-py/blob/master/dpm/client/__init__.py#L136)
- [x] Align finalize [method call](https://github.com/frictionlessdata/dpm-py/blob/master/dpm/client/__init__.py#L144) with proposed dpr-api change in https://github.com/frictionlessdata/dpr-api/issues/251 
- [x] Check the response for `finalize` method. If it is `queued`  it is success or failed.
