### ISSUE TITLE
Data validation for geojson data 

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpm-py#88]
By default we validate the data using `goodtable`. But for geojson data this validation can not be done by `goodtable`.
So while publishing geojson data we are getting invalid data type. We should add geojson
validation.

## Context and problems:

While publishing geojson data from https://github.com/frictionlessdata/example-geojson we are getting

```
Traceback (most recent call last):
  File "/usr/local/bin/dpmpy", line 4, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/dpm/main.py", line 210, in datavalidate
    report = dprclient.validate_data(dp)
  File "/usr/local/lib/python2.7/site-packages/dpm/client/__init__.py", line 333, in validate_data
    return inspector.inspect(datapackage.descriptor, preset='datapackage')
  File "/usr/local/lib/python2.7/site-packages/goodtables/inspector.py", line 89, in inspect
    errors, tables = preset_func(source, **options)
  File "/usr/local/lib/python2.7/site-packages/goodtables/presets/datapackage.py", line 44, in datapackage
    'schema': Schema(resource.descriptor['schema']),
KeyError: u'schema'
```

## Solution:

We have to find some way to validate geojson data

## Tasks:

- [ ] Search for how can we implement data validation for geojson
  - [ ] Is there some library? If yes compare and finalize what to use.
- [ ] Add validation for geojson data.

**Comment by pwalsh** [comment]
goodtables supports Table Schema and Table Schema supports a GeoJSON field type. 

Can you provide more context on what you are trying to do and why, with examples of data.

**Comment by subhankarb** [comment]
@pwalsh update the description with what problem we are facing.

**Comment by pwalsh** [comment]
Please sync up with @rufuspollock - you are confusing geojson support in a tabular data package (which goodtables can support - goodtables ONLY works with tabular data sources) with a datapackage that packages a geojson file.

**Comment by subhankarb** [comment]
This issue will be addressed in #89
