### ISSUE TITLE
Cannot upload non-tabular data as data validation fails

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpm-py#89]
We can't publish non-tabular data because we do tabular data validation of **all** resources (irrespective of type) on every publish.

More info: We validate the data prior to uploading to data package registry. Previously we focused on publishing csv data to DPR. But recently we tried geojson data and found a bug because dpmpy is throwing an error that geojson is invalid when it auto checks its validity [because it is not tabular data].

Ref: #88 

## Tasks

- [x] Write a test with a data package with some non-tabular data
- [x] Skip data validation for any non-tabular data
  - [x] Check the file type is tabular
    - [x] resources --> format (is csv)
    - [x] resources --> mediatype (text/csv)
    - [x] filename filename ends with csv.
  - [x] If non tabular skip the validation

## Acceptance Criteria:

- [ ] Non tabular data can be uploaded from command line.

## Analysis 

Options:

1. Turn off default validation and make it an optional switch
2. Skip data validation for any non-tabular data (tabular data = OR(format csv, filename ends in .csv, mediatype=text/csv)
3. Validation option for geojson data [NO]

We recommend option 1 or 2 as we do not need data validation for geojson data (right now). For now we will just implement option 2 and can revisit option 1 later if needed.

- User may not always need to check data validation
- For not tabular data we do not need data validation.
